
development:
  adapter: postgresql
  encoding: unicode
  database: final_project_development
  pool: 5
  timeout: 5000
  host: localhost
  port: 5432

test:
  adapter: postgresql
  encoding: unicode
  database: final_project_development
  pool: 5
  timeout: 5000
  host: localhost
  port: 5432

production:
  adapter: postgresql
  encoding: unicode
  database: final_project_development
  pool: 5
  timeout: 5000


