language: ruby
rvm:
  - 1.9.3
env:
  - DB=postgresql
script:
  - rake spec
before_script:
	- rake db:test:prepare
  - exec rake db:create RAILS_ENV=test
  - exec rake db:migrate
bundler_args: --binstubs=./bundler_stubs